name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      # We built already, so point app_location *to the built folder*
      # and leave output_location empty (this is the documented pattern
      # when skip_app_build: true).
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_01BB8BA1E }}
          action: upload
          app_location: dist     # <- built files folder
          output_location: ''    # <- empty when skipping app build
          skip_app_build: true
          production_branch: main

  close_pull_request_job:
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.head.repo.fork
      runs-on: ubuntu-latest
      steps:
        - name: Close Pull Request
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BAY_01BB8BA1E }}
            action: close

